#!/bin/sh

systemctl is-active ollama.service || { 
    printf "ollama.server is not active yet. I should start it? [Y/n] " 
    read ans

    if [ "$ans" = "y" ] || [ ! "$ans" = "Y" ]; then
        systemctl start ollama.service
    fi
}

podman run -d \
    --network=host \
  -v /srv/open-webui/data:/app/backend/data \
  -e OLLAMA_BASE_URL=http://localhost:11434 \
  -e WEBUI_SECRET_KEY='1145141919810' \
  -e RAG_ENABLED=false \
  -e RAG_EMBEDDING_ENGINE="" \
  -e RAG_EMBEDDING_MODEL="" \
  -e RAG_RERANKING_MODEL="" \
  --name open-webui \
  --restart unless-stopped \
  --replace \
  ghcr.io/open-webui/open-webui:main
