# Orogin: https://github.com/Mayccoll/Gogh/blob/master/themes/argonaut.sh
# Modify by @KYBNgh

background=#141719
foreground=#BEC7CF
cursor=#BEC7CF

color0=#232323
color1=#CE333C
color2=#33CE49
color3=#CEC733
color4=#3374CE
color5=#6d43a6
color6=#40AB7B
color7=#BEC7CF
color8=#444444
color9=#EE4659
color10=#5be175
color11=#ffd242
color12=#65AEF1
color13=#9a5feb
color14=#50C2E8
color15=#ffffff
