set nocompatible
set number relativenumber
set mouse=a
syntax on
filetype plugin indent on

if exists('$TMUX')
        set laststatus=1
else
        set laststatus=2
endif

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent

set viminfofile=$HOME/.local/state/vim/viminfo

call plug#begin('~/.config/vim/plugged')
    Plug 'chrisbra/Colorizer'
    Plug 'lifepillar/vim-mucomplete'
call plug#end()

let g:colorizer_auto_color = 1
let g:colorizer_auto_filetypes = ['*']

let mapleader="\\"
nmap <leader>c :ColorHighlight<CR>

set t_Co=256

highlight CursorLineNr ctermfg=blue guifg=blue cterm=bold
highlight LineNr ctermfg=darkgray guifg=darkgray
