set -g mouse on
set -g history-limit 100000
set -g status-style "bg=cyan, fg=black"

set -g window-status-style "bg=cyan, fg=black"

set -g status-left-style "bg=cyan, fg=black"
set -g status-right-style "bg=cyan, fg=black"
