# vim:ft=dosini
# ~/.config/foot/bindings.ini

[key-bindings]
font-increase=Control+equal
font-decrease=Control+minus
font-reset=Control+Shift+BackSpace

scrollback-up-half-page=Control+Shift+k
scrollback-down-half-page=Control+Shift+j

search-start=Control+slash
