# vim:ft=dosini
# ~/.config/foot/colors-dark.ini

[colors-dark]
alpha=0.9
background=141719
foreground=bec7cf

## Normal/regular colors (color palette 0-7)
regular0=232323  # black   #232323
regular1=ce333c  # red     #ce333c
regular2=33ce49  # green   #33ce49
regular3=cec733  # yellow  #cec733
regular4=65aef1  # blue    #65aef1
regular5=6d43a6  # magenta #6d43a6
regular6=50c2e8  # cyan    #50c2e8
regular7=bec7cf  # white   #bec7cf

## Bright colors (color palette 8-15)
bright0=444444   # bright black   #444444
bright1=ee4659   # bright red     #ee4659
bright2=abe15b   # bright green   #abe15b
bright3=ffd242   # bright yellow  #ffd242
bright4=0092ff   # bright blue    #0092ff
bright5=9a5feb   # bright magenta #9a5feb
bright6=3da795   # bright cyan    #3da795
bright7=ffffff   # bright white   #ffffff
