# vim:ft=dosini
# ~/.config/foot/foot.ini

include=~/.config/foot/bindings.ini
include=~/.config/foot/colors-dark.ini

font=Source Code Pro:size=18

[scrollback]
lines=32768

[mouse]
hide-when-typing=yes
