#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

flush ruleset

table inet firewall {
  chain input {
    type filter hook input priority 0;
    policy drop;

    ct state invalid drop;
    ct state established,related accept;

    iifname "lo" accept;
    iifname "tailscale0" accept;
    
    udp dport 41641 accept comment "udp: tailscale peer-to-peer";

    iifname "virbr0" udp dport { 53, 67 } accept comment "udp: libvirt dhcp/dns";
    iifname "vnet*" udp dport { 53, 67 } accept comment "udp: libvirt dhcp/dns";

    iifname "enp3s0" tcp dport 53317 accept comment "tcp: permit localsend for lan";
    iifname "enp3s0" udp dport 53317 accept comment "udp: permit localsend for lan";
    
    iifname "enp3s0" ip saddr 192.168.31.20 tcp dport 7891 accept comment "tcp: permit sshd for mobile";
    iifname "enp3s0" ip saddr 192.168.31.20 tcp dport 9090 accept comment "tcp: permit cockpit for mobile";
    iifname "enp3s0" ip saddr 192.168.31.20 tcp dport 8080 accept comment "tcp: permit openwebui for mobile";

    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept

  }

  chain forward {
    type filter hook forward priority 0;
    policy drop;

    ct state invalid drop;
    ct state established,related accept;

    iifname "virbr0" accept;
    iifname "vnet*" accept;

  }

  chain postrouting {
    type nat hook postrouting priority 100;
    policy accept;
    
    iifname "virbr0" oifname != "virbr0" masquerade
    iifname "vnet*" oifname != "virbr0" masquerade
  }

  chain output {
    type filter hook output priority 0;
    policy accept;

  }
}

