title	Arch Linux
linux	/vmlinuz-linux-lts
initrd	/amd-ucode.img
initrd	/initramfs-linux-lts.img
options	rd.luks.name=ROOTUUID=awa rd.luks.options=discard root=/dev/mapper/awa rootflags=subvol=@,compress=zstd:3,ssd,space_cache=v2,discard=async rw loglevel=3 nowatchdog zswap.enabled=0

